ALTER TABLE projects ADD COLUMN IF NOT EXISTS is_shared BOOLEAN NOT NULL DEFAULT false;
DROP TABLE IF EXISTS project_members;
DROP TYPE IF EXISTS project_role;
ALTER TABLE users DROP COLUMN IF EXISTS username;
